In [ ]:
# Naive Bayes Algorithm in Machine Learning
Naive Bayes is a probabilistic machine learning algorithm based on Bayes' theorem, which assumes that the features in a dataset are independent of each other. 
It is commonly used for classification tasks, particularly in text classification and spam filtering.
The algorithm calculates the probability of a data point belonging to a particular class based on the likelihood of the features given that class and the prior probability of the class itself.
Despite its simplicity, Naive Bayes can perform well in many real-world applications, especially when the independence assumption holds true.

## Bayes' Theorem
Bayes' theorem is a fundamental concept in probability theory that describes the relationship between conditional probabilities. It is expressed as:
P(A|B) = (P(B|A) * P(A)) / P(B)

Where:
- P(A|B) is the posterior probability of event A given that event B has occurred.
- P(B|A) is the likelihood of event B given that event A has occurred.
- P(A) is the prior probability of event A.
- P(B) is the prior probability of event B.
- In the context of Naive Bayes, A represents the class label, and B represents the features of the data point. The algorithm uses Bayes' theorem to calculate the posterior probability for each class and selects the class with the highest probability as the predicted label for the data point.

In [1]:
#import libraries
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB , MultinomialNB , BernoulliNB
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
from sklearn.datasets import load_iris

In [2]:
# load the datasets
iris = load_iris()
X = iris.data
y = iris.target


In [3]:
# split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)


In [4]:
#model initializing
GB = GaussianNB()

#model training
GB.fit(x_train,y_train)
#model prediction
y_pred = GB.predict(x_test)

#model evaluation
print("Accuracy Score : ",accuracy_score(y_test,y_pred))
print("Classification Report : \n",classification_report(y_test,y_pred))
print("Confusion Matrix : \n",confusion_matrix(y_test,y_pred))

Accuracy Score :  1.0
Classification Report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix : 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [5]:
# use multinomial Naive Bayes
MB = MultinomialNB()
MB.fit(x_train,y_train)
y_pred_MB = MB.predict(x_test)

print("Multinomial Naive Bayes Accuracy Score : ",accuracy_score(y_test,y_pred_MB))
print("Multinomial Naive Bayes Classification Report : \n",classification_report(y_test,y_pred_MB))
print("Multinomial Naive Bayes Confusion Matrix : \n",confusion_matrix(y_test,y_pred_MB))

Multinomial Naive Bayes Accuracy Score :  0.9
Multinomial Naive Bayes Classification Report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30

Multinomial Naive Bayes Confusion Matrix : 
 [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]


In [7]:
# bernoulli Naive Bayes
BB = BernoulliNB()
BB.fit(x_train,y_train)
y_pred_BB = BB.predict(x_test)

# evaluation
print("Bernoulli Naive Bayes Accuracy Score : ",accuracy_score(y_test,y_pred_BB))
print("Bernoulli Naive Bayes Classification Report : \n",classification_report(y_test,y_pred_BB))
print("Bernoulli Naive Bayes Confusion Matrix : \n",confusion_matrix(y_test,y_pred_BB))

Bernoulli Naive Bayes Accuracy Score :  0.3
Bernoulli Naive Bayes Classification Report : 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.30      1.00      0.46         9
           2       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30

Bernoulli Naive Bayes Confusion Matrix : 
 [[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]


c:\Users\mk\miniconda3\envs\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\mk\miniconda3\envs\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\mk\miniconda3\envs\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
